exports.userRouter = require("./user");
exports.wxuserRouter = require("./wx_users");
exports.userinfoRouter = require("./userinfo");
exports.groupsRouter = require("./groups");
exports.menuRouter = require("./menu");
exports.lbtRouter = require("./lbt");
exports.doctorRouter = require("./doctor");
exports.cooperationRouter = require("./cooperation");
exports.dynamicRouter = require("./dynamic");
exports.navRouter = require("./nav");
exports.user_address=require("./user_address")
exports.wx_userinfoRouter=require("./wx_userinfo")
exports.prescriptionRouter = require("./prescription");
exports.groupDataRouter = require("./medicalGroup");
exports.getwxusersRouter = require("./admin_users");
exports.mydoctorRouter = require("./my_doctor");
